# inputs.conf — Universal Forwarder
# Emplacement : C:\Program Files\SplunkUniversalForwarder\etc\system\local\inputs.conf
# Collecte des journaux d'événements Windows pour le SIEM lab

[WinEventLog://Security]
disabled = 0
index = main

[WinEventLog://System]
disabled = 0
index = main

[WinEventLog://Application]
disabled = 0
index = main

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = main
renderXml = true
